#!/usr/bin/env python3
"""Additional records to bring us past 50."""
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "standards"

RECORDS = [
    {
        "id": "STD-IEEE-2024-001",
        "date": "2024-06-10",
        "org": "IEEE SA",
        "org_full": "IEEE Standards Association",
        "jurisdiction": "us",
        "type": "consultation",
        "status": "consultation",
        "title_en": "IEEE P2848 — Standard for Verification and Validation of Automated Driving Systems",
        "title_cn": "IEEE P2848 自动驾驶系统验证与确认标准（起草中）",
        "url": "https://standards.ieee.org/ieee/2848/10908/",
        "automation_level": ["L3", "L4"],
        "topics": ["testing", "sotif"],
        "summary_en": "Draft standard defining V&V framework for ADS. Complements IEEE 2846 (safety assumptions) with concrete verification test and validation evidence requirements. Working group chaired by Mobileye and Intel.",
        "summary_cn": "起草中的自动驾驶系统验证与确认（V&V）框架标准，与 IEEE 2846（安全假设）互补，规定具体验证测试和确认证据要求。工作组由 Mobileye 和 Intel 主持。",
        "impact_note": "Expected publication 2026. Will be a key reference for US ADS safety cases.",
        "related_standards": ["IEEE 2846", "UL 4600", "SAE J3237"],
    },
    {
        "id": "STD-IEEE-2025-001",
        "date": "2025-02-18",
        "org": "IEEE SA",
        "org_full": "IEEE Standards Association",
        "jurisdiction": "us",
        "type": "consultation",
        "status": "draft",
        "title_en": "IEEE P3128 — Standard for Teleoperation of Automated Vehicles",
        "title_cn": "IEEE P3128 自动驾驶车辆远程操作标准（起草中）",
        "url": "https://standards.ieee.org/ieee/3128/11516/",
        "automation_level": ["L4"],
        "topics": ["teleoperation", "cybersecurity"],
        "summary_en": "Draft standard for teleoperation of automated vehicles. Covers tele-driving, tele-assistance, and tele-monitoring modes. Defines latency, video quality, operator qualification, cybersecurity requirements.",
        "summary_cn": "起草中的自动驾驶车辆远程操作标准，覆盖远程驾驶、远程辅助、远程监控三种模式。定义延迟、视频质量、操作员资质、网络安全要求。",
        "impact_note": "Directly relevant to Robotaxi industry. Likely template for Chinese GB/T teleoperation standard.",
        "related_standards": ["ISO 4448", "UN-R168 (future)"],
    },
    {
        "id": "STD-SAC-2025-001",
        "date": "2025-08-15",
        "org": "SAC/TC114",
        "org_full": "全国汽车标准化技术委员会",
        "jurisdiction": "china",
        "type": "consultation",
        "status": "consultation",
        "title_en": "Draft GB/T — Intelligent Connected Vehicles — Teleoperation Technical Requirements",
        "title_cn": "智能网联汽车 远程操作技术要求（征求意见稿）",
        "url": "http://www.catarc.org.cn/",
        "automation_level": ["L4"],
        "topics": ["teleoperation", "operations"],
        "summary_en": "Draft national standard for teleoperation of ICVs. Specifies latency targets (<200ms), video quality (4K, HDR), operator training, fallback procedures. Aligns with UNECE GRVA work and IEEE P3128.",
        "summary_cn": "智能网联汽车远程操作国标征求意见稿，规定延迟目标（<200ms）、视频质量（4K、HDR）、操作员培训、回退流程。与 UNECE GRVA 工作和 IEEE P3128 对齐。",
        "impact_note": "Essential for commercial Robotaxi in China. Affects Apollo Go, Pony.ai, WeRide operational playbooks.",
        "related_standards": ["IEEE P3128", "ISO 4448"],
    },
    {
        "id": "STD-ISO-2024-001",
        "date": "2024-11-07",
        "org": "ISO",
        "org_full": "International Organization for Standardization",
        "jurisdiction": "international",
        "type": "standard",
        "status": "published",
        "title_en": "ISO 34503:2024 — Road vehicles — Test scenarios for automated driving systems — Specification for operational design domain (ODD)",
        "title_cn": "ISO 34503:2024 道路车辆 自动驾驶系统测试场景 运行设计域（ODD）规范",
        "url": "https://www.iso.org/standard/78952.html",
        "effective_date": "2024-11-07",
        "automation_level": ["L3", "L4"],
        "topics": ["testing", "sotif"],
        "summary_en": "Defines a hierarchical vocabulary and format for specifying ODD of an ADS. Addresses lack of standardized ODD description that had hampered cross-OEM scenario libraries.",
        "summary_cn": "定义自动驾驶系统 ODD（运行设计域）的层级词汇和格式，解决此前 OEM 间场景库缺乏统一 ODD 描述的问题。",
        "impact_note": "Required reading for L3/L4 validation. Enables cross-OEM scenario library sharing. BSI PAS 1883 preceded this with similar structure.",
        "related_standards": ["ISO 34502", "BSI PAS 1883"],
    },
    {
        "id": "STD-ISO-2025-001",
        "date": "2025-06-15",
        "org": "ISO",
        "org_full": "International Organization for Standardization",
        "jurisdiction": "international",
        "type": "consultation",
        "status": "consultation",
        "title_en": "ISO/DIS 21448:2025 — SOTIF Revision (DIS stage)",
        "title_cn": "ISO/DIS 21448:2025 预期功能安全修订（DIS 阶段）",
        "url": "https://www.iso.org/standard/91001.html",
        "automation_level": ["L1", "L2", "L3", "L4"],
        "topics": ["sotif", "functional_safety"],
        "summary_en": "Draft International Standard for revised SOTIF. Strengthens requirements for AI/ML component validation, runtime monitoring, and integration with cybersecurity (ISO/SAE 21434).",
        "summary_cn": "ISO 21448 修订的 DIS 阶段草案，加强对 AI/ML 组件验证、运行时监测、与网络安全（ISO/SAE 21434）集成的要求。",
        "impact_note": "Expected publication 2026. Major update for modern ADS using deep learning perception/planning.",
        "related_standards": ["ISO 21448:2022", "ISO/SAE 21434", "ISO/IEC 42001"],
    },
    {
        "id": "STD-MIIT-2024-001",
        "date": "2024-07-31",
        "org": "MIIT",
        "org_full": "中华人民共和国工业和信息化部",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "Notice on Approving First Batch of L3/L4 Pilot Entities (9 Consortia)",
        "title_cn": "关于公布首批智能网联汽车准入和上路通行试点联合体名单的通知",
        "url": "https://www.miit.gov.cn/",
        "effective_date": "2024-07-31",
        "automation_level": ["L3", "L4"],
        "topics": ["operations", "type_approval"],
        "summary_en": "Approves first 9 consortia (OEM + city + operator) for the L3/L4 pilot program. Includes BYD-Shenzhen-Pony.ai, NIO-Shanghai-NIO, Changan-Chongqing, BAIC-Beijing, SAIC-Shanghai, Dongfeng-Wuhan, GAC-Guangzhou, Yutong-Zhengzhou, Beijing-Yutong.",
        "summary_cn": "公布 L3/L4 首批 9 个试点联合体（车企+城市+运营方）名单，涵盖比亚迪-深圳-小马智行、蔚来-上海-蔚来、长安-重庆、北汽-北京、上汽-上海、东风-武汉、广汽-广州、宇通-郑州、北京-宇通。",
        "impact_note": "Marks transition from testing to commercial deployment. Chinese L3/L4 market access now has clear regulatory anchor.",
        "related_standards": ["MIIT 2023-217"],
    },
    {
        "id": "STD-CAERI-2025-001",
        "date": "2025-03-10",
        "org": "CAERI",
        "org_full": "中国汽车工程研究院",
        "jurisdiction": "china",
        "type": "white_paper",
        "status": "published",
        "title_en": "i-VISTA 2025 — NCA (Navigate on City Autopilot) Assessment Protocol",
        "title_cn": "i-VISTA 2025 NCA（城市领航辅助驾驶）测评规程",
        "url": "http://www.i-vista.org/",
        "effective_date": "2025-03-10",
        "automation_level": ["L2"],
        "topics": ["testing"],
        "summary_en": "First Chinese consumer assessment protocol specifically for urban NoA features. Tests 34 scenarios including unprotected left turns, cyclist interaction, construction zones, emergency vehicles. Huawei HIMA, Xiaomi, NIO, Li Auto, XPeng graded.",
        "summary_cn": "中国首个专门针对城市 NoA（领航辅助驾驶）功能的消费者测评规程，测试 34 个场景：无保护左转、骑行者交互、施工区域、紧急车辆等。华为 HIMA、小米、蔚来、理想、小鹏均接受评级。",
        "impact_note": "Tightly scrutinized by Chinese consumers and media. Shapes the L2+ market perception in China.",
        "related_standards": ["C-NCAP 2024", "Euro NCAP AD"],
    },
    {
        "id": "STD-EC-2025-001",
        "date": "2025-03-01",
        "org": "European Commission",
        "org_full": "European Commission - DG MOVE",
        "jurisdiction": "eu",
        "type": "consultation",
        "status": "consultation",
        "title_en": "Call for Evidence — Revised EU General Safety Regulation (GSR-II) 2028+",
        "title_cn": "欧盟第二代通用安全法规（GSR-II）2028+ 证据征集",
        "url": "https://transport.ec.europa.eu/",
        "effective_date": "2025-03-01",
        "automation_level": ["L2", "L3"],
        "topics": ["type_approval", "functional_safety"],
        "summary_en": "Consultation on next-generation EU General Safety Regulation, scheduled post-2028. Considers mandatory L3 safety features, enhanced AEB, pedestrian/cyclist protection refinements, integration with AI Act requirements.",
        "summary_cn": "欧盟第二代通用安全法规（2028 后）征求意见。考虑强制 L3 安全功能、加强 AEB、细化行人/骑行者保护、与 AI Act 要求整合。",
        "impact_note": "Will shape EU vehicle regulation through 2030s. Critical for OEM product planning cycle.",
    },
    {
        "id": "STD-UK-2025-001",
        "date": "2025-07-10",
        "org": "UK DfT",
        "org_full": "UK Department for Transport",
        "jurisdiction": "uk",
        "type": "consultation",
        "status": "consultation",
        "title_en": "Draft Secondary Legislation — UK Automated Vehicles Act 2024 Implementation",
        "title_cn": "英国 2024 年自动驾驶汽车法案实施的附属立法草案",
        "url": "https://www.gov.uk/government/consultations/",
        "automation_level": ["L3", "L4"],
        "topics": ["type_approval", "operations"],
        "summary_en": "DfT consultation on secondary legislation implementing the 2024 AV Act. Defines ASDE application procedures, insurance requirements, in-use enforcement, Automated Passenger Service (APS) framework.",
        "summary_cn": "交通部对实施 2024 年《自动驾驶汽车法案》附属立法的征求意见。明确 ASDE 申请程序、保险要求、使用期监管、APS（自动载客服务）框架。",
        "impact_note": "Determines when UK Robotaxi services can launch. Expected to open market to Waymo, Wayve, Oxbotica (now Oxa) post 2026.",
        "related_standards": ["UK AV Act 2024"],
    },
    {
        "id": "STD-METI-2025-001",
        "date": "2025-06-13",
        "org": "METI Japan",
        "org_full": "Ministry of Economy, Trade and Industry of Japan",
        "jurisdiction": "japan",
        "type": "policy",
        "status": "in_force",
        "title_en": "Mobility Roadmap 2025 — Updated Targets and Level 4 Deployment Priorities",
        "title_cn": "日本 2025 年交通出行路线图：更新的目标与 Level 4 部署优先领域",
        "url": "https://www.meti.go.jp/english/press/2025/0613_001.html",
        "effective_date": "2025-06-13",
        "automation_level": ["L4"],
        "topics": ["operations", "type_approval"],
        "summary_en": "2025 update of Japan's mobility roadmap. Maintains 100-location target for 2027, clarifies funding mechanisms, introduces a collaboration framework with local municipalities.",
        "summary_cn": "日本交通出行路线图 2025 更新版，维持 2027 年 100 个地点部署目标，明确资助机制，引入与地方政府的协作框架。",
        "impact_note": "Signals Japan's commitment to L4 beyond Tokyo-Nagoya corridor. Attracts Chinese and US technology providers (Tier Ⅳ, Waymo, Pony.ai).",
        "related_standards": ["Japan MLIT 2024 Safety Guidelines"],
    },
    {
        "id": "STD-NCAP-2024-001",
        "date": "2024-03-26",
        "org": "Euro NCAP",
        "org_full": "European New Car Assessment Programme",
        "jurisdiction": "eu",
        "type": "standard",
        "status": "in_force",
        "title_en": "Euro NCAP 2026 Vision — New Scoring Weighting for ADAS/AD",
        "title_cn": "Euro NCAP 2026 愿景：ADAS/AD 新评分权重",
        "url": "https://www.euroncap.com/en/vehicle-safety/safety-campaigns/2026-roadmap/",
        "effective_date": "2026-01-01",
        "automation_level": ["L1", "L2", "L3"],
        "topics": ["testing"],
        "summary_en": "Euro NCAP's 2026 rating scheme increases weighting on 'Safe Driving' (ADAS/AD) from 25% to 30%. Introduces new categories for AD consumer assessment effective 2026 model year onward.",
        "summary_cn": "Euro NCAP 2026 评分方案将'安全驾驶'（ADAS/AD）权重从 25% 提升到 30%，自 2026 年款车型起引入新的 AD 消费者评估类别。",
        "impact_note": "Direct financial incentive for OEMs to deploy advanced L2+ features. All major Chinese OEMs targeting EU affected.",
    },
]

CONTRIBUTOR = "AD Standards Tracker Seed / Zhang Yuxin"
LAST_UPDATED = "2026-04-16"


def main() -> None:
    written = 0
    for r in RECORDS:
        r.setdefault("contributor", CONTRIBUTOR)
        r.setdefault("last_updated", LAST_UPDATED)
        year = r["date"][:4]
        directory = OUT / r["jurisdiction"] / year
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / f"{r['id']}.yaml"
        with open(path, "w", encoding="utf-8") as f:
            yaml.safe_dump(r, f, allow_unicode=True, sort_keys=False, default_flow_style=False, width=120)
        written += 1
    total = sum(1 for _ in OUT.rglob("*.yaml"))
    print(f"Wrote {written} additional records; total YAML files: {total}")


if __name__ == "__main__":
    main()
