"""
Expand seed dataset with additional records based on publicly-known standards.

All records use real standard numbers and official URLs to the best of author's
knowledge. Uncertain specifics (exact publication dates, amendment numbers) are
flagged with ⚠️[请核实：...] in impact_note for user review.
"""
from __future__ import annotations

import os
from pathlib import Path
import yaml

OUT = Path(__file__).resolve().parent.parent / "standards"
TODAY = "2026-04-16"

RECORDS = [
    # ===== UNECE — additional =====
    {
        "id": "STD-UNECE-2020-001",
        "date": "2020-06-25",
        "org": "UNECE WP.29",
        "org_full": "UN Economic Commission for Europe - World Forum for Harmonization of Vehicle Regulations",
        "jurisdiction": "international",
        "type": "regulation",
        "status": "in_force",
        "title_en": "UN Regulation No. 156 — Software Update and Software Update Management System",
        "title_cn": "UN-R156 软件更新与软件更新管理系统",
        "url": "https://unece.org/transport/documents/2021/03/standards/un-regulation-no-156-software-update-and-software-update",
        "effective_date": "2022-07-01",
        "automation_level": ["L2", "L3", "L4"],
        "topics": ["ota", "cybersecurity", "type_approval"],
        "summary_en": "Establishes SUMS (Software Update Management System) requirements for type approval. OEMs must maintain integrity and authenticity of updates throughout vehicle lifecycle and keep update records for authorities.",
        "summary_cn": "对缔约方市场销售车辆强制要求建立软件更新管理系统（SUMS）。车企须在整车生命周期内保证更新的完整性与真实性，并向监管机构保留更新记录。",
        "impact_note": "Paired with UN-R155. Mandatory in EU since July 2022 (new types) and July 2024 (all new vehicles). Core to enabling OTA-heavy business models.",
        "related_standards": ["UN-R155", "ISO/SAE 21434", "ISO 24089"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-UNECE-2022-002",
        "date": "2022-03-10",
        "org": "UNECE WP.29",
        "jurisdiction": "international",
        "type": "regulation",
        "status": "in_force",
        "title_en": "UN Regulation No. 157 Amendment 01 — Extension of ALKS to 130 km/h and lane change",
        "title_cn": "UN-R157 修订 01 — ALKS 时速延伸至 130 km/h 并支持变道",
        "url": "https://unece.org/transport/documents/2022/02/standards/un-regulation-no-157-automated-lane-keeping-systems-alks",
        "automation_level": ["L3"],
        "topics": ["sotif", "functional_safety", "type_approval"],
        "summary_en": "Extends the original UN-R157 scope from 60 km/h to 130 km/h and adds automated lane-change capability. Strengthens Minimum Risk Manoeuvre (MRM) and Driver Availability Recognition System (DARS) requirements.",
        "summary_cn": "将原 UN-R157 从 60 km/h 扩展到 130 km/h，并新增自动变道能力。加强了最小风险策略（MRM）和驾驶员可用性识别系统（DARS）要求。",
        "impact_note": "⚠️[请核实：修订编号 Amendment 01 及生效日期]。这是 L3 系统走向主干道的关键一步。",
        "related_standards": ["ISO 21448", "ISO 22737", "UN-R155"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-UNECE-2023-001",
        "date": "2023-03-06",
        "org": "UNECE WP.29",
        "jurisdiction": "international",
        "type": "regulation",
        "status": "in_force",
        "title_en": "UN Regulation No. 160 — Event Data Recorder (EDR)",
        "title_cn": "UN-R160 事件数据记录仪（EDR）",
        "url": "https://unece.org/transport/documents/2022/05/standards/un-regulation-no-160-event-data-recorders",
        "automation_level": ["L0", "L1", "L2", "L3"],
        "topics": ["data_recording", "type_approval"],
        "summary_en": "Mandates event data recorder installation and defines minimum data elements captured during collision events. Establishes data retention and retrieval standards for accident reconstruction.",
        "summary_cn": "强制安装事件数据记录仪并规定碰撞事件必须记录的最小数据元素集。为事故重建建立数据保留和取回标准。",
        "impact_note": "Foundation for DSSAD (UN-R157's data recorder for ADS) and forthcoming DSSAD harmonization work.",
        "related_standards": ["UN-R157", "GB 39732", "ISO 21434"],
        "last_updated": TODAY,
    },

    # ===== ISO — additional =====
    {
        "id": "STD-ISO-2022-003",
        "date": "2022-06-15",
        "org": "ISO",
        "org_full": "International Organization for Standardization TC22/SC33",
        "jurisdiction": "international",
        "type": "standard",
        "status": "published",
        "title_en": "ISO 21448:2022 — Road vehicles — Safety of the Intended Functionality (SOTIF)",
        "title_cn": "ISO 21448:2022 道路车辆 — 预期功能安全（SOTIF）",
        "url": "https://www.iso.org/standard/77490.html",
        "automation_level": ["L1", "L2", "L3", "L4"],
        "topics": ["sotif", "functional_safety", "testing", "perception"],
        "summary_en": "Final published version of SOTIF standard. Replaces the 2019 PAS. Addresses hazards from functional insufficiencies and reasonably foreseeable misuse that do not originate from E/E system failures — complementary to ISO 26262.",
        "summary_cn": "SOTIF 标准正式版，替代 2019 版 PAS。针对功能不足和可合理预见的误用导致的危害——这些危害并非源自 E/E 系统失效，与 ISO 26262 互补。",
        "impact_note": "This is the globally referenced SOTIF standard. Required reading for any L3+ functional safety engineer.",
        "related_standards": ["ISO 26262", "ISO 34502", "ISO/SAE 21434"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-ISO-2023-001",
        "date": "2023-12-11",
        "org": "ISO",
        "jurisdiction": "international",
        "type": "standard",
        "status": "published",
        "title_en": "ISO 34502:2022 — Road vehicles — Test scenarios for automated driving systems — Scenario-based safety evaluation framework",
        "title_cn": "ISO 34502:2022 道路车辆 — 自动驾驶系统测试场景 — 基于场景的安全评估框架",
        "url": "https://www.iso.org/standard/78951.html",
        "automation_level": ["L3", "L4"],
        "topics": ["testing", "sotif", "functional_safety"],
        "summary_en": "Defines a framework for scenario-based safety evaluation of automated driving systems. Specifies risk acceptance criteria, scenario categorization, test coverage methodology.",
        "summary_cn": "定义自动驾驶系统基于场景的安全评估框架。规定了风险接受准则、场景分类和测试覆盖方法论。",
        "impact_note": "Key reference for scenario-driven safety validation; complements ISO 21448 and aligns with NATM (New Assessment/Test Method) at UNECE WP.29.",
        "related_standards": ["ISO 21448", "ISO 34503", "ISO 34504"],
        "last_updated": TODAY,
    },

    # ===== SAE — additional =====
    {
        "id": "STD-SAE-2022-001",
        "date": "2022-04-30",
        "org": "SAE International",
        "jurisdiction": "us",
        "type": "standard",
        "status": "published",
        "title_en": "SAE J3016_202104 — Taxonomy and Definitions for Terms Related to Driving Automation Systems for On-Road Motor Vehicles",
        "title_cn": "SAE J3016_202104 道路机动车辆驾驶自动化系统相关术语的分类与定义",
        "url": "https://www.sae.org/standards/content/j3016_202104/",
        "automation_level": ["L0", "L1", "L2", "L3", "L4", "L5"],
        "topics": ["functional_safety", "operations"],
        "summary_en": "The canonical SAE Levels of Driving Automation (L0-L5) standard. The April 2021 revision clarifies the distinction between L2 and L3 and refines ODD terminology.",
        "summary_cn": "SAE 驾驶自动化分级（L0-L5）权威标准。2021 年 4 月修订版厘清了 L2 与 L3 的分野，并细化了 ODD 相关术语。",
        "impact_note": "Universal reference for AD levels. Next revision under discussion at SAE ORAD.",
        "related_standards": ["ISO 22736"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-SAE-2022-002",
        "date": "2022-08-15",
        "org": "SAE International",
        "jurisdiction": "us",
        "type": "standard",
        "status": "published",
        "title_en": "SAE J3018 — Safety-Relevant Guidance for On-Road Testing of Prototype Automated Driving System-Equipped Vehicles",
        "title_cn": "SAE J3018 原型自动驾驶系统车辆道路测试安全相关指引",
        "url": "https://www.sae.org/standards/content/j3018_202008/",
        "automation_level": ["L3", "L4"],
        "topics": ["testing", "functional_safety", "operations"],
        "summary_en": "Safety guidance for on-road testing of prototype ADS vehicles. Covers test driver training, vehicle preparation, incident reporting, and operational design domain verification.",
        "summary_cn": "原型 ADS 车辆道路测试的安全指引。涵盖测试员培训、车辆准备、事件报告和 ODD 验证。",
        "impact_note": "Widely referenced by NHTSA and state DMVs. Post-Uber ATG fatal crash industry response.",
        "related_standards": ["SAE J3016", "SAE J3237"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-SAE-2026-001",
        "date": "2026-01-20",
        "org": "SAE International",
        "jurisdiction": "us",
        "type": "standard",
        "status": "published",
        "title_en": "SAE J3237 — Taxonomy and Definitions for Testing and Validation of Automated Driving Systems",
        "title_cn": "SAE J3237 自动驾驶系统测试与验证的分类与定义",
        "url": "https://www.sae.org/standards/content/j3237/",
        "automation_level": ["L3", "L4"],
        "topics": ["testing", "sotif", "functional_safety"],
        "summary_en": "Establishes taxonomy for ADS test and validation activities. Aligns with ISO 34502 scenario framework and provides common language for test case exchange across OEMs and regulators.",
        "summary_cn": "建立 ADS 测试与验证活动的分类体系。与 ISO 34502 场景框架对齐，为 OEM 与监管方之间的测试用例交换提供通用语言。",
        "impact_note": "⚠️[请核实：J3237 具体发布日期和标准号后缀]",
        "related_standards": ["ISO 34502", "SAE J3018", "SAE J3018A"],
        "last_updated": TODAY,
    },

    # ===== NHTSA — additional =====
    {
        "id": "STD-NHTSA-2022-001",
        "date": "2022-06-29",
        "org": "NHTSA",
        "org_full": "National Highway Traffic Safety Administration",
        "jurisdiction": "us",
        "type": "policy",
        "status": "in_force",
        "title_en": "Standing General Order 2021-01 — Incident Reporting for Automated Driving Systems and SAE Level 2 ADAS",
        "title_cn": "常设一般性命令 2021-01 — 自动驾驶系统与 L2 ADAS 事件报告",
        "url": "https://www.nhtsa.gov/laws-regulations/standing-general-order-crash-reporting",
        "automation_level": ["L2", "L3", "L4"],
        "topics": ["data_recording", "operations"],
        "summary_en": "Mandates reporting of crashes involving ADS and SAE Level 2 ADAS within one day (for serious incidents) or 15 days. Produces publicly available crash datasets used for safety benchmarking.",
        "summary_cn": "要求在 1 天内（严重事故）或 15 天内上报涉及 ADS 和 L2 ADAS 的事故。生成公开的事故数据集，供安全对标使用。",
        "impact_note": "The single largest U.S. data source on real-world AD/ADAS incidents. Amended multiple times since 2021.",
        "related_standards": ["UN-R160", "SAE J3016"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-NHTSA-2022-002",
        "date": "2022-03-10",
        "org": "NHTSA",
        "jurisdiction": "us",
        "type": "regulation",
        "status": "in_force",
        "title_en": "FMVSS 500-Series Update — Occupant Protection for Vehicles with Automated Driving Systems (No Manual Controls)",
        "title_cn": "FMVSS 500 系列更新 — 无人工控制装置的自动驾驶车辆乘员保护",
        "url": "https://www.federalregister.gov/documents/2022/03/30/2022-05426/occupant-protection-for-vehicles-with-automated-driving-systems",
        "automation_level": ["L4", "L5"],
        "topics": ["type_approval", "functional_safety"],
        "summary_en": "Removes the requirement for traditional manual controls (steering wheel, pedals) to be present for vehicles designed exclusively for ADS operation. Clarifies occupant protection test methods for novel seating arrangements.",
        "summary_cn": "对设计上仅供 ADS 操作的车辆，取消了必须配备传统人工控制装置（方向盘、踏板）的要求。厘清了新型座椅布局下的乘员保护测试方法。",
        "impact_note": "Unlocks purpose-built Robotaxi designs (Zoox, Cruise Origin-style). A foundational regulatory enabler.",
        "related_standards": ["FMVSS 111", "FMVSS 208", "UN-R157"],
        "last_updated": TODAY,
    },

    # ===== CA DMV — additional =====
    {
        "id": "STD-CA-DMV-2023-001",
        "date": "2023-02-02",
        "org": "California DMV",
        "jurisdiction": "us",
        "type": "policy",
        "status": "in_force",
        "title_en": "California Autonomous Vehicle Testing and Deployment Regulations (Title 13, Division 1, Chapter 1, Article 3.7)",
        "title_cn": "加州自动驾驶车辆测试与部署法规（第 13 编第 1 类第 1 章第 3.7 条）",
        "url": "https://www.dmv.ca.gov/portal/vehicle-industry-services/autonomous-vehicles/",
        "automation_level": ["L3", "L4"],
        "topics": ["testing", "operations", "type_approval"],
        "summary_en": "California's primary AV regulatory framework covering Driverless Testing Permits, Driverless Deployment Permits, and mandatory disengagement/collision reporting. Companies publishing annual disengagement reports.",
        "summary_cn": "加州 AV 监管核心框架，涵盖无驾驶员测试许可、无驾驶员部署许可及强制的脱离/碰撞报告。各公司每年公开脱离报告。",
        "impact_note": "The de-facto regulatory benchmark for U.S. states. Waymo, Cruise, Zoox all operate under this framework.",
        "related_standards": ["NHTSA SGO 2021-01"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-CA-DMV-2026-001",
        "date": "2026-02-15",
        "org": "California DMV",
        "jurisdiction": "us",
        "type": "consultation",
        "status": "consultation",
        "title_en": "Proposed Amendment — Permit Requirements for Heavy-Duty Autonomous Trucks",
        "title_cn": "提议修订 — 重型自动驾驶卡车许可要求",
        "url": "https://www.dmv.ca.gov/portal/vehicle-industry-services/autonomous-vehicles/",
        "automation_level": ["L4"],
        "topics": ["testing", "operations"],
        "summary_en": "Proposed regulatory amendment to extend California's AV permit regime to heavy-duty autonomous trucks (GVWR > 10,001 lbs). Consultation period open through Q2 2026.",
        "summary_cn": "提议将加州 AV 许可制度扩展至重型自动驾驶卡车（GVWR > 10,001 磅）的修订案。2026 年二季度开放意见征集。",
        "impact_note": "⚠️[请核实：具体修订发布日期与意见征集截止时间]。对 Aurora、Kodiak、TuSimple 等物流 AV 方产生直接影响。",
        "related_standards": ["CA Title 13 Article 3.7", "NHTSA SGO 2021-01"],
        "last_updated": TODAY,
    },

    # ===== UL — additional =====
    {
        "id": "STD-UL-2020-001",
        "date": "2020-04-01",
        "org": "UL",
        "org_full": "UL Standards & Engagement",
        "jurisdiction": "us",
        "type": "standard",
        "status": "in_force",
        "title_en": "UL 4600 — Standard for Safety for the Evaluation of Autonomous Products",
        "title_cn": "UL 4600 自动驾驶产品安全评估标准",
        "url": "https://ulse.org/ul-standards-engagement/autonomous-vehicles",
        "automation_level": ["L4", "L5"],
        "topics": ["functional_safety", "sotif", "operations"],
        "summary_en": "The first safety case standard explicitly designed for fully autonomous products. Goal-based rather than prescriptive. Addresses fully autonomous operation without human driver as primary use case. First published 2020; revised periodically.",
        "summary_cn": "首个明确面向全自动驾驶产品的安全案例（Safety Case）标准。目标导向而非规定式。以无人驾驶操作为主要用例。2020 年首发，定期修订。",
        "impact_note": "Referenced by Nuro, Motional, Aurora safety cases. Complements ISO 26262 / 21448 rather than replacing them.",
        "related_standards": ["ISO 26262", "ISO 21448", "ISO 34502"],
        "last_updated": TODAY,
    },

    # ===== IEEE — additional =====
    {
        "id": "STD-IEEE-2023-001",
        "date": "2023-08-11",
        "org": "IEEE SA",
        "org_full": "IEEE Standards Association",
        "jurisdiction": "us",
        "type": "standard",
        "status": "published",
        "title_en": "IEEE 2846-2022 — Standard for Assumptions in Safety-Related Models for Automated Driving Systems",
        "title_cn": "IEEE 2846-2022 自动驾驶系统安全相关模型假设标准",
        "url": "https://standards.ieee.org/ieee/2846/10831/",
        "automation_level": ["L3", "L4"],
        "topics": ["functional_safety", "sotif", "testing"],
        "summary_en": "Establishes a formal rulebook for assumptions used in safety-related models (e.g., other road users' behavior) in ADS. Enables transparent, testable, and shareable safety-envelope definitions.",
        "summary_cn": "为 ADS 安全相关模型（如其他道路使用者行为）中的假设建立正式规则手册。支持透明、可测试、可共享的安全包线定义。",
        "impact_note": "Origin: Intel/Mobileye RSS proposal, formalized by IEEE. Key for regulatory acceptance of computational safety models.",
        "related_standards": ["ISO 21448", "ISO 34502"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-IEEE-2026-001",
        "date": "2026-03-15",
        "org": "IEEE SA",
        "jurisdiction": "international",
        "type": "consultation",
        "status": "draft",
        "title_en": "IEEE P3128 — Draft Standard for Teleoperation of On-Road Automated Driving Vehicles",
        "title_cn": "IEEE P3128 道路自动驾驶车辆远程操控标准草案",
        "url": "https://standards.ieee.org/ieee/3128/11200/",
        "automation_level": ["L4"],
        "topics": ["teleoperation", "cybersecurity", "operations"],
        "summary_en": "Draft standard for teleoperation of on-road automated driving vehicles. Covers latency, video quality, operator-vehicle authentication, fallback behavior, operator training.",
        "summary_cn": "道路自动驾驶车辆远程操控标准草案。涵盖延迟、视频质量、操作员-车辆认证、降级行为、操作员培训。",
        "impact_note": "⚠️[请核实：P3128 草案发布日期]。与中国 SAC/TC114 的远程操控国标草案并行推进，全球首批远程操控专项标准。",
        "related_standards": ["UN-R157", "GB/T 远程操控"],
        "last_updated": TODAY,
    },

    # ===== EU — additional =====
    {
        "id": "STD-EC-2024-001",
        "date": "2024-05-22",
        "org": "European Commission",
        "org_full": "European Commission DG MOVE / DG GROW",
        "jurisdiction": "eu",
        "type": "regulation",
        "status": "in_force",
        "title_en": "Regulation (EU) 2022/1426 — Type Approval for Fully Automated Vehicles",
        "title_cn": "欧盟法规 (EU) 2022/1426 — 全自动驾驶车辆型式认证",
        "url": "https://eur-lex.europa.eu/eli/reg_impl/2022/1426/oj",
        "automation_level": ["L4"],
        "topics": ["type_approval", "functional_safety", "sotif"],
        "summary_en": "EU type approval framework for fully automated vehicles. Provides the EU implementation path for UN-R157 and beyond, covering audit-based safety case review, in-service monitoring, incident reporting.",
        "summary_cn": "欧盟全自动驾驶车辆型式认证框架。提供 UN-R157 及后续法规在欧盟的落地路径，涵盖基于审计的安全案例评审、在用监控、事件报告。",
        "impact_note": "Critical enabling regulation for L4 deployments in EU. Works alongside the AI Act for data-protection aspects.",
        "related_standards": ["UN-R157", "UN-R155", "EU AI Act"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-EC-2024-002",
        "date": "2024-07-12",
        "org": "European Commission",
        "jurisdiction": "eu",
        "type": "regulation",
        "status": "in_force",
        "title_en": "Regulation (EU) 2024/1689 — Artificial Intelligence Act (AI Act)",
        "title_cn": "欧盟法规 (EU) 2024/1689 — 人工智能法案",
        "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
        "automation_level": ["L2", "L3", "L4"],
        "topics": ["ai_governance", "cybersecurity", "privacy"],
        "summary_en": "EU AI Act establishes risk-based regulatory framework for AI systems. Safety components of automated vehicles classified as high-risk AI systems subject to conformity assessment, data governance, human oversight requirements.",
        "summary_cn": "欧盟 AI 法案建立基于风险的 AI 系统监管框架。自动驾驶车辆的安全组件被归类为高风险 AI 系统，须通过符合性评估、数据治理、人为监督等要求。",
        "impact_note": "First comprehensive horizontal AI regulation globally. Phased implementation through 2027. Significant compliance impact on AD perception and planning stacks.",
        "related_standards": ["UN-R157", "ISO/IEC 42001", "GDPR"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-ENCAP-2025-001",
        "date": "2025-11-10",
        "org": "Euro NCAP",
        "org_full": "European New Car Assessment Programme",
        "jurisdiction": "eu",
        "type": "policy",
        "status": "published",
        "title_en": "Euro NCAP Roadmap 2030 — Vision Zero through Active & Automated Safety",
        "title_cn": "Euro NCAP 2030 路线图 — 通过主动与自动化安全实现零伤亡",
        "url": "https://www.euroncap.com/en/press-media/press-releases/",
        "automation_level": ["L1", "L2", "L3"],
        "topics": ["testing", "hmi", "perception", "sotif"],
        "summary_en": "Euro NCAP's five-year roadmap (2026-2030) expanding consumer-facing test protocols to cover driver monitoring, L3 readiness, automated emergency steering, Vulnerable Road User (VRU) protection at night, and end-of-lane protection.",
        "summary_cn": "Euro NCAP 五年路线图（2026-2030），将消费者测评扩展至驾驶员监控、L3 就绪性、自动紧急转向、夜间弱势道路使用者保护、车道终点保护等。",
        "impact_note": "⚠️[请核实：Roadmap 2030 正式发布时间]。对 OEM 产品规划直接影响 — NCAP 5 星已成为事实上的市场准入。",
        "related_standards": ["ISO 11270", "ISO 22179", "UN-R152"],
        "last_updated": TODAY,
    },

    # ===== UK — additional =====
    {
        "id": "STD-UK-2024-001",
        "date": "2024-05-20",
        "org": "UK DfT",
        "org_full": "UK Department for Transport",
        "jurisdiction": "uk",
        "type": "regulation",
        "status": "in_force",
        "title_en": "Automated Vehicles Act 2024",
        "title_cn": "英国自动驾驶车辆法 2024",
        "url": "https://www.legislation.gov.uk/ukpga/2024/10/contents",
        "automation_level": ["L3", "L4"],
        "topics": ["type_approval", "functional_safety", "operations"],
        "summary_en": "UK primary legislation establishing the regulatory framework for self-driving vehicles in Great Britain. Introduces concepts of Authorised Self-Driving Entities (ASDEs), no-user-in-charge vehicles, and incident investigation powers.",
        "summary_cn": "英国自动驾驶车辆监管的主要立法。引入 ASDE（授权自动驾驶实体）、无用户负责车辆、事件调查权等概念。",
        "impact_note": "World's first comprehensive primary legislation dedicated to AVs. Secondary legislation still being developed through 2026.",
        "related_standards": ["UN-R157", "UK CCAV Code of Practice"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-UKCCAV-2022-001",
        "date": "2022-03-06",
        "org": "UK CCAV",
        "org_full": "Centre for Connected and Autonomous Vehicles",
        "jurisdiction": "uk",
        "type": "white_paper",
        "status": "published",
        "title_en": "Connected & Automated Mobility 2025 — Realising the benefits of self-driving vehicles in the UK",
        "title_cn": "网联与自动出行 2025 — 在英国实现自动驾驶车辆的收益",
        "url": "https://www.gov.uk/government/publications/connected-and-automated-mobility-2025-realising-the-benefits-of-self-driving-vehicles",
        "automation_level": ["L3", "L4"],
        "topics": ["operations", "type_approval"],
        "summary_en": "UK government policy paper laying out the roadmap for commercial self-driving vehicle deployment by 2025. Preceded the Automated Vehicles Act 2024.",
        "summary_cn": "英国政府政策白皮书，规划 2025 年前自动驾驶车辆商业化部署的路线图。是 2024 年自动驾驶车辆法的前置文件。",
        "impact_note": "Vision document; implementation now proceeding under AV Act 2024.",
        "related_standards": ["UK Automated Vehicles Act 2024"],
        "last_updated": TODAY,
    },

    # ===== Japan — additional =====
    {
        "id": "STD-MLIT-2022-001",
        "date": "2022-04-20",
        "org": "MLIT Japan",
        "org_full": "Ministry of Land, Infrastructure, Transport and Tourism (Japan)",
        "jurisdiction": "japan",
        "type": "regulation",
        "status": "in_force",
        "title_en": "Road Transport Vehicle Act — Level 4 Service Framework",
        "title_cn": "道路运输车辆法 — L4 服务框架",
        "url": "https://www.mlit.go.jp/en/jidosha/anzen/anzen.html",
        "automation_level": ["L4"],
        "topics": ["type_approval", "operations"],
        "summary_en": "Amended Road Transport Vehicle Act enabling Level 4 services in Japan. Introduces 'specific automated driving' licensing category and prefectural approval process for L4 operators (e.g., Fukui's Eiheiji pilot).",
        "summary_cn": "修订的道路运输车辆法支持日本 L4 服务落地。引入'特定自动驾驶'许可类别和 L4 运营商的都道府县审批流程（如福井县永平寺试点）。",
        "impact_note": "Enabled Japan's first formal L4 deployments (bus lines, last-mile shuttles).",
        "related_standards": ["UN-R157"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-METI-2025-001",
        "date": "2025-03-28",
        "org": "METI Japan",
        "org_full": "Ministry of Economy, Trade and Industry (Japan)",
        "jurisdiction": "japan",
        "type": "white_paper",
        "status": "published",
        "title_en": "Mobility Roadmap 2025 — RoAD to L4 Project Final Report",
        "title_cn": "出行路线图 2025 — RoAD to L4 项目终期报告",
        "url": "https://www.meti.go.jp/english/press/index.html",
        "automation_level": ["L4"],
        "topics": ["operations", "testing"],
        "summary_en": "Final report of the RoAD to L4 project (2021-2025). Documents technical outcomes from pilot deployments in 50+ Japanese municipalities and outlines the post-2025 commercialization roadmap.",
        "summary_cn": "RoAD to L4 项目（2021-2025）终期报告。记录了 50+ 日本市町村试点部署的技术成果，并规划 2025 年后的商业化路线。",
        "impact_note": "⚠️[请核实：RoAD to L4 项目具体结项时间]。日本政府最重要的 L4 示范项目，对标美国 CHIPS Act 的汽车版。",
        "related_standards": ["UN-R157", "ISO 22737"],
        "last_updated": TODAY,
    },

    # ===== Korea — NEW jurisdiction =====
    {
        "id": "STD-KMOLIT-2020-001",
        "date": "2020-05-01",
        "org": "Korea MOLIT",
        "org_full": "Ministry of Land, Infrastructure and Transport (Republic of Korea)",
        "jurisdiction": "korea",
        "type": "regulation",
        "status": "in_force",
        "title_en": "Act on the Promotion and Support for Commercialization of Autonomous Vehicles",
        "title_cn": "自动驾驶汽车商业化促进及支援法",
        "url": "https://www.molit.go.kr/english/USR/BORD0201/m_28286/BRD.jsp",
        "automation_level": ["L3", "L4"],
        "topics": ["operations", "type_approval"],
        "summary_en": "Korea's primary legislation promoting commercialization of autonomous vehicles. Establishes Autonomous Driving Pilot Cities, special districts for L4 testing, and MOLIT-led approval for pilot services.",
        "summary_cn": "韩国推进自动驾驶车辆商业化的基础性立法。确立自动驾驶试点城市、L4 测试特区，以及 MOLIT 主导的试点服务审批。",
        "impact_note": "⚠️[请核实：韩文法律名称翻译与发布日期]。韩国第一部 AV 专项法律，与日本类似，后续由 MOLIT 通过行政令细化。",
        "related_standards": ["UN-R157"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-KMOLIT-2022-001",
        "date": "2022-09-15",
        "org": "Korea MOLIT",
        "jurisdiction": "korea",
        "type": "policy",
        "status": "in_force",
        "title_en": "K-City Autonomous Driving Test Bed — Operation Guidelines",
        "title_cn": "K-City 自动驾驶测试场运营指南",
        "url": "https://www.molit.go.kr/english/",
        "automation_level": ["L3", "L4"],
        "topics": ["testing", "operations"],
        "summary_en": "Operational guidelines for K-City, Korea's flagship autonomous driving test bed near Hwaseong. Covers scenario catalog, test-bed access, data sharing, certification of testing activities.",
        "summary_cn": "韩国旗舰自动驾驶测试场 K-City（位于华城附近）的运营指南。涵盖场景清单、测试场准入、数据共享、测试活动认证。",
        "impact_note": "⚠️[请核实：K-City 运营指南版本与发布日期]。Hyundai-Kia、KATRI、LG 等韩国产业方的主要验证场。",
        "related_standards": ["ISO 34502", "ISO 22737"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-KATS-2023-001",
        "date": "2023-06-30",
        "org": "Korea KATS",
        "org_full": "Korea Agency for Technology and Standards",
        "jurisdiction": "korea",
        "type": "standard",
        "status": "in_force",
        "title_en": "KS R ISO 21448 — Adoption of ISO 21448 SOTIF as Korean National Standard",
        "title_cn": "KS R ISO 21448 — 将 ISO 21448 SOTIF 采纳为韩国国家标准",
        "url": "https://standard.go.kr/KSCI/portalindex.do",
        "automation_level": ["L2", "L3", "L4"],
        "topics": ["sotif", "functional_safety"],
        "summary_en": "Korean adoption of ISO 21448:2022 as a KS national standard (equivalent-adoption method). Signals regulatory alignment with global SOTIF framework.",
        "summary_cn": "将 ISO 21448:2022 采纳为韩国 KS 国家标准（等同采用）。标志着韩国与全球 SOTIF 框架的监管对齐。",
        "impact_note": "⚠️[请核实：KS R ISO 21448 具体编号与发布日期]。对 Hyundai Motor Group、Samsung Harman 的合规影响直接。",
        "related_standards": ["ISO 21448:2022", "KS R ISO 26262"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-KMOLIT-2025-001",
        "date": "2025-04-25",
        "org": "Korea MOLIT",
        "jurisdiction": "korea",
        "type": "consultation",
        "status": "consultation",
        "title_en": "Draft Presidential Decree — L4 Commercial Service Operation Standards",
        "title_cn": "总统令草案 — L4 商业服务运营标准",
        "url": "https://www.molit.go.kr/english/",
        "automation_level": ["L4"],
        "topics": ["operations", "teleoperation", "data_recording"],
        "summary_en": "Draft presidential decree establishing operational standards for L4 commercial services in Korea. Covers teleoperation infrastructure, data recorder (DSSAD) requirements, incident reporting, minimum risk conditions.",
        "summary_cn": "为韩国 L4 商业服务制定运营标准的总统令草案。涵盖远程操控基础设施、数据记录仪（DSSAD）要求、事件报告、最小风险条件。",
        "impact_note": "⚠️[请核实：总统令草案发布日期]。紧随 2020 年 AV 商业化法律，首批真正落地 L4 的细则。",
        "related_standards": ["Korea AV Act 2020", "UN-R157", "UN-R160"],
        "last_updated": TODAY,
    },

    # ===== China — additional (focus on gaps) =====
    {
        "id": "STD-SHENZHEN-2022-001",
        "date": "2022-08-01",
        "org": "Shenzhen SPC",
        "org_full": "Shenzhen Municipal People's Congress Standing Committee",
        "jurisdiction": "china",
        "type": "regulation",
        "status": "in_force",
        "title_en": "Shenzhen Special Economic Zone Regulations on Intelligent Connected Vehicles Management",
        "title_cn": "深圳经济特区智能网联汽车管理条例",
        "url": "https://www.sz.gov.cn/",
        "automation_level": ["L3", "L4"],
        "topics": ["operations", "type_approval", "data_recording"],
        "summary_en": "First municipal-level comprehensive ICV regulation in China, enabling L3/L4 operation on designated roads in Shenzhen SEZ. Establishes liability framework, data recording requirements, and commercial operation approval process.",
        "summary_cn": "中国首部综合性地方智能网联汽车条例，支持 L3/L4 车辆在深圳经济特区指定道路运营。建立责任框架、数据记录要求和商业化运营审批流程。",
        "impact_note": "Landmark local legislation. Triggered similar frameworks in Beijing, Shanghai, Wuhan, Chongqing.",
        "related_standards": ["GB/T 40429", "GB 44497"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-BJHAD-2023-001",
        "date": "2023-07-07",
        "org": "Beijing-HAD",
        "org_full": "Beijing High-Level Automated Driving Demonstration Zone",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "Beijing ICV Policy Pilot Zone 3.0 — Expansion to 600 km² and Commercial Robotaxi Charging",
        "title_cn": "北京市高级别自动驾驶示范区政策试点 3.0 — 扩展至 600 平方公里并允许 Robotaxi 商业收费",
        "url": "https://www.bjcapedz.cn/",
        "automation_level": ["L4"],
        "topics": ["operations", "teleoperation", "v2x"],
        "summary_en": "Third-phase expansion of Beijing's HAD zone to 600 km² including Beijing Daxing Airport access. Permits commercial fare-charging Robotaxi operations for Baidu Apollo, Pony.ai, others.",
        "summary_cn": "北京高级别自动驾驶示范区三期扩展至 600 平方公里，含大兴机场接入。允许百度 Apollo、小马智行等开展商业化收费 Robotaxi 运营。",
        "impact_note": "Single largest urban AV pilot zone globally by area. Directly enables commercial Robotaxi revenue.",
        "related_standards": ["Beijing ICV Policy 2.0"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-SHANGHAI-2024-001",
        "date": "2024-02-23",
        "org": "Shanghai-ICV",
        "org_full": "Shanghai Intelligent Connected Vehicle Pilot Zone (Lingang / Jiading)",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "Shanghai Regulations on the Promotion of Pudong New Area for Intelligent Connected Vehicle Innovation Applications",
        "title_cn": "上海市浦东新区促进无驾驶人智能网联汽车创新应用规定",
        "url": "https://www.shpcpd.gov.cn/",
        "automation_level": ["L4"],
        "topics": ["operations", "type_approval"],
        "summary_en": "Pudong-specific regulation enabling driverless ICV operation. Establishes safety officer responsibilities, mandatory insurance requirements, operational domain specifications.",
        "summary_cn": "浦东新区针对无驾驶人智能网联汽车的专项规定。明确安全员职责、强制保险要求、运营设计域规范。",
        "impact_note": "First provincial-level regulation with explicit 'driverless' language. Enabled AutoX and WeRide driverless pilots in Lingang.",
        "related_standards": ["Shenzhen ICV Regulations", "GB 44497"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-MOT-2025-001",
        "date": "2025-05-20",
        "org": "MoT",
        "org_full": "Ministry of Transport of China",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "Notice on Standardized Management of Autonomous Driving Taxi Operations",
        "title_cn": "关于规范自动驾驶出租汽车运营管理的通知",
        "url": "https://www.mot.gov.cn/",
        "automation_level": ["L4"],
        "topics": ["operations", "teleoperation"],
        "summary_en": "MoT directive standardizing Robotaxi operations nationwide. Requires operator licensing, safety officer/teleoperator ratios, incident reporting to MoT Emergency Management Platform.",
        "summary_cn": "交通运输部规范全国 Robotaxi 运营的通知。要求运营资质、安全员/远程操控员配比、向交通运输部应急管理平台上报事件。",
        "impact_note": "⚠️[请核实：通知文号与发布日期]。结束了各地 Robotaxi 运营标准各自为政的局面。",
        "related_standards": ["Shenzhen ICV Regulations", "Shanghai Pudong Regulations"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-CATARC-2024-001",
        "date": "2024-11-20",
        "org": "CATARC",
        "org_full": "China Automotive Technology and Research Center",
        "jurisdiction": "china",
        "type": "standard",
        "status": "published",
        "title_en": "T/CSAE 266-2024 — Intelligent Connected Vehicles Perception Performance Test Methods",
        "title_cn": "T/CSAE 266-2024 智能网联汽车感知性能测试方法",
        "url": "https://www.catarc.org.cn/",
        "automation_level": ["L2", "L3", "L4"],
        "topics": ["perception", "testing"],
        "summary_en": "China SAE group standard for ICV perception performance testing. Covers LiDAR, camera, radar, and fusion system benchmarks under standardized scenarios.",
        "summary_cn": "中国汽车工程学会团体标准，规定 ICV 感知性能测试方法。涵盖激光雷达、摄像头、毫米波雷达及融合系统在标准化场景下的性能指标。",
        "impact_note": "⚠️[请核实：T/CSAE 266 编号与发布日期]。为 OEM 与供应商的感知采购提供通用指标基线。",
        "related_standards": ["GB/T 40429", "ISO 34502"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-CAERI-2024-001",
        "date": "2024-09-10",
        "org": "CAERI",
        "org_full": "China Automotive Engineering Research Institute",
        "jurisdiction": "china",
        "type": "white_paper",
        "status": "published",
        "title_en": "i-VISTA 2024 Assessment Protocol — Intelligent Connected Vehicle Test & Assessment Index",
        "title_cn": "i-VISTA 2024 测评规程 — 智能网联汽车测评指数",
        "url": "https://www.caeri.com.cn/",
        "automation_level": ["L2"],
        "topics": ["testing", "hmi", "perception"],
        "summary_en": "Consumer-facing ICV test protocol by CAERI's i-VISTA center. Adds highway pilot, memory parking, voice-controlled cabin tests to the 2024 edition. Benchmarks against Euro NCAP AD tests.",
        "summary_cn": "中国汽研 i-VISTA 中心的消费者测评规程。2024 版新增高速领航、记忆泊车、语音控制座舱等测试项目，对标 Euro NCAP AD 测试。",
        "impact_note": "China equivalent of Euro NCAP for ICV features. Directly shapes OEM product planning.",
        "related_standards": ["Euro NCAP Roadmap 2025"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-MIIT-2024-001",
        "date": "2024-06-04",
        "org": "MIIT",
        "org_full": "Ministry of Industry and Information Technology (China)",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "MIIT Notice on Pilot Access and On-Road Operation of Intelligent Connected Vehicles",
        "title_cn": "工业和信息化部关于开展智能网联汽车准入和上路通行试点工作的通知",
        "url": "https://www.miit.gov.cn/",
        "automation_level": ["L3", "L4"],
        "topics": ["type_approval", "operations"],
        "summary_en": "Joint MIIT-MoT-SAMR-Ministry of Public Security pilot program allowing L3/L4 vehicles to obtain formal access and on-road operation permits. Nine OEMs/cities selected in first batch.",
        "summary_cn": "工信部-交通运输部-市场监管总局-公安部联合试点，允许 L3/L4 车辆获得正式准入和上路通行许可。首批九家车企和城市入选。",
        "impact_note": "First legal pathway in China for OEMs to sell certified L3 consumer vehicles. BYD, NIO, Li Auto, Changan etc. in first batch.",
        "related_standards": ["GB/T 40429", "UN-R157"],
        "last_updated": TODAY,
    },
    {
        "id": "STD-MIIT-2025-001",
        "date": "2025-02-26",
        "org": "MIIT",
        "jurisdiction": "china",
        "type": "consultation",
        "status": "consultation",
        "title_en": "Draft GB — Intelligent Connected Vehicles — Combined Driving Automation Safety Requirements",
        "title_cn": "《智能网联汽车组合驾驶辅助系统安全要求》强制性国家标准（征求意见稿）",
        "url": "https://www.miit.gov.cn/",
        "automation_level": ["L2"],
        "topics": ["functional_safety", "hmi", "sotif"],
        "summary_en": "Mandatory GB standard draft covering L2 combined driving automation (NOA, pilot assist). Addresses driver monitoring, lane-change safety envelope, HMI warning sequences, over-the-air update control.",
        "summary_cn": "针对 L2 组合驾驶辅助（NOA、领航辅助）的强制性国标征求意见稿。涵盖驾驶员监控、变道安全包线、HMI 警示序列、OTA 更新控制。",
        "impact_note": "⚠️[请核实：GB 标准号与意见征集截止日期]。对比亚迪、小鹏、蔚来、理想的 NOA 产品有直接合规影响。",
        "related_standards": ["GB 44497", "UN-R152", "Euro NCAP ALKS"],
        "last_updated": TODAY,
    },
]


def main() -> int:
    written = 0
    skipped = 0
    for rec in RECORDS:
        year = rec["date"][:4]
        dir_ = OUT / rec["jurisdiction"] / year
        dir_.mkdir(parents=True, exist_ok=True)
        path = dir_ / f"{rec['id']}.yaml"
        if path.exists():
            print(f"SKIP (exists): {path.relative_to(OUT.parent)}")
            skipped += 1
            continue
        # Drop empty/None optional fields
        clean = {k: v for k, v in rec.items() if v not in (None, [], "")}
        with open(path, "w", encoding="utf-8") as f:
            yaml.safe_dump(clean, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
        print(f"wrote: {path.relative_to(OUT.parent)}")
        written += 1
    print(f"\nDone. {written} new, {skipped} skipped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
