#!/usr/bin/env python3
"""Seed Chinese standard records."""
import os
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "standards"

RECORDS = [
    {
        "id": "STD-SAC-2024-001",
        "date": "2024-03-25",
        "org": "SAC/TC114",
        "org_full": "全国汽车标准化技术委员会 / National Technical Committee of Auto Standardization",
        "jurisdiction": "china",
        "type": "standard",
        "status": "in_force",
        "title_en": "GB/T 44373-2024 — Intelligent Connected Vehicles — Terms and Definitions",
        "title_cn": "GB/T 44373-2024 智能网联汽车 术语和定义",
        "url": "https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=E5D49F73A1226AB06CE60E7BD47A2BDC",
        "effective_date": "2024-10-01",
        "automation_level": ["L0", "L1", "L2", "L3", "L4", "L5"],
        "topics": ["type_approval"],
        "summary_en": "China's foundational national standard for ICV terminology. Defines automated driving levels (aligned with SAE J3016), ADS, ADAS, remote operations, minimum risk maneuver, and other core terms used across all subsequent GB and GB/T ICV standards.",
        "summary_cn": "中国智能网联汽车术语的基础性国家标准，定义自动驾驶等级（与 SAE J3016 对齐）、ADS、ADAS、远程运营、最小风险策略等后续所有 GB/GB/T 智能网联汽车标准所引用的核心术语。",
        "impact_note": "All Chinese ICV standards reference this vocabulary. Sole source for regulatory automation-level classification in China.",
        "related_standards": ["SAE J3016", "ISO 22737"],
    },
    {
        "id": "STD-SAC-2024-002",
        "date": "2024-05-15",
        "org": "SAC/TC114",
        "org_full": "全国汽车标准化技术委员会",
        "jurisdiction": "china",
        "type": "standard",
        "status": "in_force",
        "title_en": "GB 44497-2024 — Intelligent Connected Vehicles — Automated Driving Data Recording System",
        "title_cn": "GB 44497-2024 智能网联汽车 自动驾驶数据记录系统",
        "url": "https://openstd.samr.gov.cn/bzgk/gb/",
        "effective_date": "2025-01-01",
        "automation_level": ["L3", "L4"],
        "topics": ["data_recording", "functional_safety"],
        "summary_en": "Mandatory standard for automated driving data recording systems (DSSAD equivalent). Defines data elements, recording conditions, storage, and retrieval. Prerequisite for L3/L4 type approval in China.",
        "summary_cn": "强制性国家标准，规定自动驾驶数据记录系统（类似 DSSAD）的数据元素、记录条件、存储与读取。是中国 L3/L4 型式认证的前置条件。",
        "impact_note": "Referenced by the April 2026 draft GB/T Safety Events Data Interaction Technical Specification (the standard you analyzed in our April 17 CATARC meeting document).",
        "related_standards": ["GB 39732", "ISO 21434", "UN-R157"],
    },
    {
        "id": "STD-SC34-2026-001",
        "date": "2026-04-13",
        "org": "SAC/TC114/SC34",
        "org_full": "全国汽车标准化技术委员会智能网联汽车分技术委员会",
        "jurisdiction": "china",
        "type": "meeting_notice",
        "status": "consultation",
        "title_en": "Standards Project Meeting Notice — Intelligent Connected Vehicles Safety Events Data Interaction and Management System Technical Specification",
        "title_cn": "《智能网联汽车 安全事件数据交互与管理系统技术规范》标准项目组会议通知（汽标智联字〔2026〕66 号）",
        "url": "http://www.catarc.org.cn/",
        "effective_date": "2026-04-17",
        "automation_level": ["L2", "L3", "L4"],
        "topics": ["data_recording", "operations", "functional_safety"],
        "summary_en": "Notice of April 17, 2026 Beijing meeting to discuss the draft GB/T Technical Specification on ICV Safety Events Data Interaction and Management System. Draft defines 14 event type codes (0x01-0x0E), enterprise-to-national platform reporting architecture, SM2/SM4 cryptographic requirements.",
        "summary_cn": "2026 年 4 月 17 日北京会议通知，讨论《智能网联汽车 安全事件数据交互与管理系统技术规范》国标草案。草案定义 14 种事件编码（0x01-0x0E）、企业平台→国家平台上报架构、SM2/SM4 国密加密要求。"
        ,
        "impact_note": "Direct trigger for ROAM's GB/T alignment analysis. Zhang Yuxin (Jilin University) submitted a comparative analysis to the secretariat on 2026-04-16. See roam.autozyx.com.",
        "related_standards": ["GB 44497", "GB 39732", "UN-R155"],
    },
    {
        "id": "STD-MIIT-2022-001",
        "date": "2022-08-08",
        "org": "MIIT",
        "org_full": "中华人民共和国工业和信息化部",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "Notice on Strengthening Management of Intelligent Connected Vehicle Product Access, Recall and Network Security",
        "title_cn": "关于加强智能网联汽车生产企业及产品准入管理的意见（工信部装〔2022〕132 号）",
        "url": "https://www.miit.gov.cn/jgsj/zbgys/qcgy/art/2022/art_98bdbee6a0fa4a8a9b63e3b4c0f4a18d.html",
        "effective_date": "2022-08-08",
        "automation_level": ["L2", "L3", "L4"],
        "topics": ["type_approval", "cybersecurity", "data_recording"],
        "summary_en": "MIIT policy strengthening ICV type approval. Requires OTA update approval, cybersecurity reporting, safety incident reporting, data security compliance. First comprehensive Chinese regulatory framework for ICV market access.",
        "summary_cn": "工信部加强智能网联汽车准入管理的综合性政策，要求 OTA 升级审批、网络安全报备、安全事件报告、数据安全合规。是中国首个综合性智能网联汽车市场准入监管框架。",
        "impact_note": "Foundational regulation cited by every subsequent GB/T ICV standard. Precedent for 2026 Safety Events Data Interaction draft.",
        "related_standards": ["GB 44497", "GB/T 44373"],
    },
    {
        "id": "STD-MIIT-2023-001",
        "date": "2023-11-17",
        "org": "MIIT",
        "org_full": "中华人民共和国工业和信息化部",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "Notice on Launching Pilot of Access and On-Road Traffic for Intelligent Connected Vehicles (L3/L4)",
        "title_cn": "关于开展智能网联汽车准入和上路通行试点工作的通知（工信部联装〔2023〕217 号）",
        "url": "https://www.miit.gov.cn/",
        "effective_date": "2023-11-17",
        "automation_level": ["L3", "L4"],
        "topics": ["type_approval", "operations"],
        "summary_en": "Joint MIIT/MoT/MPS/MOHURD notice launching the national L3/L4 ICV access and on-road operation pilot. Defines five stages: application, access, pilot operation, assessment, confirmation.",
        "summary_cn": "工信部、交通运输部、公安部、住建部联合发布，启动 L3/L4 智能网联汽车准入和上路通行试点。定义五阶段：申请、准入、试点、评估、确认。",
        "impact_note": "Opened regulatory pathway for mass production L3 in China. Enabled BMW-Brilliance L3 in Shanghai 2023-12 and broader OEM applications in 2024.",
        "related_standards": ["GB 44497", "UN-R157"],
    },
    {
        "id": "STD-MoT-2022-001",
        "date": "2022-08-08",
        "org": "MoT",
        "org_full": "中华人民共和国交通运输部",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "Guidelines on Promoting Intelligent Connected Vehicle Road Testing and Demonstration Applications",
        "title_cn": "关于促进道路交通自动驾驶安全发展的指导意见（交科技发〔2022〕103 号）",
        "url": "https://www.mot.gov.cn/zhengceku/",
        "effective_date": "2022-08-08",
        "automation_level": ["L3", "L4"],
        "topics": ["operations", "testing"],
        "summary_en": "MoT guidance on road testing and demonstration applications for ICVs. Covers Robotaxi commercial trials, autonomous bus operations, autonomous freight pilots. Defines safety supervisor requirements.",
        "summary_cn": "交通运输部关于促进道路交通自动驾驶安全发展的指导意见，涵盖 Robotaxi 商业化试点、自动驾驶公交运营、自动驾驶货运试点，定义安全员要求。",
        "impact_note": "Foundation for Apollo Go and Pony.ai commercial operations in Wuhan, Beijing, Guangzhou.",
        "related_standards": ["GB/T 44373", "MoT [2018] 145"],
    },
    {
        "id": "STD-CATARC-2024-001",
        "date": "2024-07-01",
        "org": "CATARC",
        "org_full": "中国汽车技术研究中心有限公司 / China Automotive Technology and Research Center",
        "jurisdiction": "china",
        "type": "white_paper",
        "status": "published",
        "title_en": "C-NCAP 2024 — Assisted Driving Protocol (AD Protocol v1.0)",
        "title_cn": "C-NCAP 2024 辅助驾驶测评规程 v1.0",
        "url": "https://www.catarc.com/",
        "effective_date": "2024-07-01",
        "automation_level": ["L2"],
        "topics": ["testing"],
        "summary_en": "C-NCAP expands beyond passive/active safety into L2 assisted driving assessment. Protocol tests lane keeping, adaptive cruise, AEB at different speeds, NoA (Navigate on Autopilot) handover behavior.",
        "summary_cn": "C-NCAP 从被动/主动安全扩展到 L2 辅助驾驶测评。方案测试车道保持、自适应巡航、不同速度下的 AEB、NoA 接管行为。",
        "impact_note": "Chinese counterpart to Euro NCAP Assisted Driving protocol. Affects marketing of L2+ systems by Chinese OEMs (BYD, NIO, XPeng, Li Auto, Huawei HIMA).",
        "related_standards": ["Euro NCAP", "i-VISTA"],
    },
    {
        "id": "STD-CAERI-2023-001",
        "date": "2023-11-15",
        "org": "CAERI",
        "org_full": "中国汽车工程研究院 / China Automotive Engineering Research Institute",
        "jurisdiction": "china",
        "type": "white_paper",
        "status": "published",
        "title_en": "i-VISTA Intelligent Connected Vehicle Assessment System 2023",
        "title_cn": "i-VISTA 智能网联汽车测评体系 2023",
        "url": "http://www.i-vista.org/",
        "effective_date": "2023-11-15",
        "automation_level": ["L2", "L3"],
        "topics": ["testing"],
        "summary_en": "Chongqing-based consumer assessment scheme for ICVs. Tests AEB, ACC, LKA, TJP (traffic jam pilot), HWP (highway pilot), parking assist. Annual public rankings influence Chinese consumer purchases.",
        "summary_cn": "重庆主办的智能网联汽车消费者测评体系，测试 AEB、ACC、LKA、TJP（交通拥堵辅助）、HWP（高速公路辅助）、自动泊车。年度公开排名影响中国消费者选车。",
        "impact_note": "Considered the most rigorous Chinese public ICV assessment. Huawei HIMA, Tesla Model Y, Li Auto L9 all tested.",
        "related_standards": ["Euro NCAP", "C-NCAP"],
    },
    {
        "id": "STD-SZ-2022-001",
        "date": "2022-06-23",
        "org": "Shenzhen SPC",
        "org_full": "深圳市人民代表大会常务委员会",
        "jurisdiction": "china",
        "type": "regulation",
        "status": "in_force",
        "title_en": "Shenzhen Special Economic Zone Intelligent Connected Vehicle Management Regulation",
        "title_cn": "深圳经济特区智能网联汽车管理条例",
        "url": "http://www.szrd.gov.cn/",
        "effective_date": "2022-08-01",
        "automation_level": ["L3", "L4"],
        "topics": ["type_approval", "operations"],
        "summary_en": "China's first local ICV legislation with statutory force. Explicitly permits fully driverless operation in designated zones, clarifies liability (vehicle owner for L3 with safety driver, enterprise for L4 driverless), establishes data reporting obligations.",
        "summary_cn": "中国首个具有法定效力的智能网联汽车地方立法。明确允许特定区域全无人运营，划分责任（L3 有安全员时车主责任，L4 全无人时企业责任），规定数据上报义务。",
        "impact_note": "Served as template for other Chinese cities. Influenced 2023 MIIT national pilot policy.",
        "related_standards": ["Beijing HAD Zone Rules", "Shanghai Lingang ICV Rules"],
    },
    {
        "id": "STD-BJ-2024-001",
        "date": "2024-12-31",
        "org": "Beijing-HAD",
        "org_full": "北京市高级别自动驾驶示范区（亦庄）",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "Beijing HAD Zone 3.0 Plan — Expanding L4 Operations Coverage in 2025",
        "title_cn": "北京市高级别自动驾驶示范区 3.0 方案 — 2025 年 L4 运营覆盖扩展",
        "url": "https://www.bjcapedz.cn/",
        "effective_date": "2025-01-01",
        "automation_level": ["L4"],
        "topics": ["operations"],
        "summary_en": "Beijing's Yizhuang HAD Zone 3.0 expands from the original 60 km² core area to 600+ km² city-wide operation. Supports Apollo Go, Pony.ai, WeRide, AutoX commercial Robotaxi services plus autonomous freight from Novauto, Xincheng, and others.",
        "summary_cn": "北京亦庄高级别自动驾驶示范区 3.0 方案，从原 60 平方公里核心区扩展到全市 600+ 平方公里。支持萝卜快跑、小马智行、文远知行、AutoX 商业 Robotaxi，以及新石器、小马智行自动驾驶货运。",
        "impact_note": "Largest L4 operational domain in China by area. Shapes the regulatory model copied by Wuhan, Shenzhen, Shanghai.",
        "related_standards": ["Shenzhen ICV Regulation", "Wuhan ICV Pilot"],
    },
    {
        "id": "STD-SH-2024-001",
        "date": "2024-07-01",
        "org": "Shanghai-ICV",
        "org_full": "上海市临港新片区/嘉定区智能网联汽车示范区",
        "jurisdiction": "china",
        "type": "policy",
        "status": "in_force",
        "title_en": "Shanghai Lingang & Jiading ICV Demonstration Zone — L3 Pilot Implementation Details",
        "title_cn": "上海市临港/嘉定智能网联汽车示范区 L3 试点实施细则",
        "url": "https://www.shcaeri.com/",
        "effective_date": "2024-07-01",
        "automation_level": ["L3"],
        "topics": ["operations", "type_approval"],
        "summary_en": "Shanghai's implementation rules for the national L3 pilot. Approves SAIC, NIO, IM Motors for L3 highway and urban pilots. Defines insurance, safety supervisor (for early stages), and incident reporting obligations.",
        "summary_cn": "上海市针对国家 L3 试点的实施细则，批准上汽、蔚来、智己开展 L3 高速与城市场景试点。定义保险、安全员（试点初期）、事件报告义务。",
        "impact_note": "Shanghai hosts China's largest OEM R&D concentration; affects the pace of nationwide L3 rollout.",
        "related_standards": ["MIIT 2023-217", "UN-R157"],
    },

    # === Additional International / Other ===
    {
        "id": "STD-UNECE-2024-001",
        "date": "2024-09-20",
        "org": "UNECE WP.29",
        "org_full": "UN Economic Commission for Europe - Working Party WP.29/GRVA",
        "jurisdiction": "international",
        "type": "research",
        "status": "published",
        "title_en": "GRVA Task Force on Regulatory Fitness for Automated Driving Systems — Status Report",
        "title_cn": "UNECE GRVA 自动驾驶法规适应性工作组状态报告",
        "url": "https://unece.org/sites/default/files/2025-09/GRVA-23-35e.pdf",
        "effective_date": "2024-09-20",
        "automation_level": ["L3", "L4"],
        "topics": ["type_approval"],
        "summary_en": "GRVA working document reviewing gaps between current UN Regulations and future L4 urban operation needs. Identifies priority areas: teleoperation, MRM handover, data reporting harmonization, validation methods.",
        "summary_cn": "GRVA 工作组文件，审视当前联合国法规与未来 L4 城市运营需求的差距，识别优先领域：远程操作、MRM 交接、数据上报协调、验证方法。",
        "impact_note": "Frames the 2025-2027 UN-R evolution roadmap. Informs both US and Chinese national regulators.",
        "related_standards": ["UN-R157", "ISO 34502"],
    },
    {
        "id": "STD-UNECE-2025-001",
        "date": "2025-09-22",
        "org": "UNECE WP.29",
        "org_full": "UN Economic Commission for Europe - Working Party WP.29/GRVA",
        "jurisdiction": "international",
        "type": "meeting_notice",
        "status": "published",
        "title_en": "WP.29/GRVA 23rd Session Agenda — September 2025",
        "title_cn": "UNECE WP.29/GRVA 第 23 届会议议程（2025 年 9 月）",
        "url": "https://unece.org/transport/events/wp29grva-23rd-session",
        "effective_date": "2025-09-22",
        "automation_level": ["L3", "L4"],
        "topics": ["type_approval"],
        "summary_en": "Agenda for GRVA 23rd session covering UN-R157 amendments (urban environment expansion), new framework for ADS validation, cybersecurity ongoing work. Hosts from Japan, Germany, US, China, Korea.",
        "summary_cn": "GRVA 第 23 届会议议程，议题包括 UN-R157 修订（城市环境扩展）、ADS 验证新框架、网络安全持续工作。主要参会国家：日本、德国、美国、中国、韩国。",
        "impact_note": "Sets tone for global L4 regulation. Attendance increasingly important for Chinese OEMs pursuing international market access.",
    },

    # === More US / FMVSS ===
    {
        "id": "STD-NHTSA-2023-001",
        "date": "2023-10-26",
        "org": "NHTSA",
        "org_full": "National Highway Traffic Safety Administration",
        "jurisdiction": "us",
        "type": "recall",
        "status": "in_force",
        "title_en": "Cruise Recall 23E-0062 — All Robotaxi Fleet due to Post-Crash Response Behavior",
        "title_cn": "Cruise 召回 23E-0062 因事故后处置行为缺陷召回全部 Robotaxi 车队",
        "url": "https://www.nhtsa.gov/recalls",
        "effective_date": "2023-11-08",
        "automation_level": ["L4"],
        "topics": ["operations", "functional_safety"],
        "summary_en": "Federal recall of 950 Cruise Robotaxis following the October 2023 pedestrian dragging incident in San Francisco. Firmware update changes post-collision behavior to avoid secondary harm. Coupled with CA DMV suspension.",
        "summary_cn": "2023 年 10 月旧金山行人拖拽事件后，对 950 辆 Cruise Robotaxi 的联邦召回。固件升级改变事故后行为以避免二次伤害。同步触发加州 DMV 的运营许可吊销。",
        "impact_note": "Landmark federal enforcement. Ended Cruise's mainstream Robotaxi business. ROAM-2023-001 incident directly linked.",
        "related_standards": ["NHTSA SGO", "CA DMV OL316"],
    },
    {
        "id": "STD-SAE-2023-001",
        "date": "2023-05-22",
        "org": "SAE International",
        "org_full": "SAE International",
        "jurisdiction": "us",
        "type": "standard",
        "status": "published",
        "title_en": "SAE J3018 — Safety-Relevant Guidance for On-Road Testing of Prototype Automated Driving Systems",
        "title_cn": "SAE J3018 原型自动驾驶系统道路测试的安全相关指南",
        "url": "https://www.sae.org/standards/content/j3018/",
        "effective_date": "2023-05-22",
        "automation_level": ["L3", "L4"],
        "topics": ["testing"],
        "summary_en": "Recommended practice for safety of prototype ADS during on-road testing. Safety driver qualification, test vehicle requirements, incident reporting, ODD management.",
        "summary_cn": "原型自动驾驶系统道路测试的安全建议实践，涵盖安全员资质、测试车辆要求、事件报告、ODD 管理。",
        "impact_note": "Broadly followed by US/CA/AZ testing programs. Chinese national demonstration zones align on similar principles.",
        "related_standards": ["SAE J3206"],
    },

    # === More China (SAMR + more standards) ===
    {
        "id": "STD-SAMR-2024-001",
        "date": "2024-12-31",
        "org": "SAMR",
        "org_full": "国家市场监督管理总局",
        "jurisdiction": "china",
        "type": "consultation",
        "status": "consultation",
        "title_en": "Draft GB — Performance Requirements and Test Methods for Intelligent Connected Vehicles (Passenger Cars) Combined Driving Automation Systems (L2)",
        "title_cn": "智能网联汽车 组合驾驶辅助系统 性能要求及试验方法（乘用车）征求意见稿",
        "url": "https://openstd.samr.gov.cn/bzgk/gb/",
        "automation_level": ["L2"],
        "topics": ["testing", "type_approval"],
        "summary_en": "Draft mandatory GB standard defining performance and test requirements for L2 combined ADAS in passenger cars. Consultation period closed Q1 2025; expected enactment 2026.",
        "summary_cn": "强制性 GB 国标草案，定义乘用车 L2 组合辅助驾驶系统的性能与试验要求。征求意见于 2025 年 Q1 截止，预计 2026 年实施。",
        "impact_note": "Will dramatically raise bar for L2 ADAS certification in China. Affects all Chinese OEMs marketing 'NoA', 'NGP', 'NCA' features.",
        "related_standards": ["UN-R79", "Euro NCAP AD Protocol"],
    },
]

CONTRIBUTOR = "AD Standards Tracker Seed / Zhang Yuxin"
LAST_UPDATED = "2026-04-16"


def main() -> None:
    written = 0
    for r in RECORDS:
        r.setdefault("contributor", CONTRIBUTOR)
        r.setdefault("last_updated", LAST_UPDATED)
        year = r["date"][:4]
        directory = OUT / r["jurisdiction"] / year
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / f"{r['id']}.yaml"
        with open(path, "w", encoding="utf-8") as f:
            yaml.safe_dump(
                r,
                f,
                allow_unicode=True,
                sort_keys=False,
                default_flow_style=False,
                width=120,
            )
        written += 1
    total = sum(1 for _ in OUT.rglob("*.yaml"))
    print(f"Wrote {written} China + additional records; total YAML files: {total}")


if __name__ == "__main__":
    main()
